### ISSUE TITLE
Caching the metal-hammer and partition boot kernel

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-image-cache-sync#3]
We often see that the download from Github assets is fairly slow. It can sometimes take up to 20 minutes to PXE boot a machine inside our partitions in some locations. From this perspective, it would be beneficial if we could also cache the metal-hammer and the boot kernel inside a partition.

However, this feature mixes up concerns. If we do this, we should require to mount a separate directory into the container in order not to interfere with the existing OS image caching and try to strictly separate concerns. From deployment perspective this feature will also make things much more complicated. I am not fully sure how this should look like and if it makes sense.

**Comment by majst01** [comment]
Happy to help here
